### PR TITLE
Polish translation for ADV - ACE CPR

### PR DESCRIPTION
**Pull request by veteran29**
Polish translation strings for ADV - ACE CPR

### CODE REVIEW

**Comment by Pergor** [comment]
Thank you very much for the translation! Has been integrated in https://github.com/Pergor/ADV_Medical/commit/596aa0733957a7ddc0691402a62eb9c43bfdb9b3
Since my Polish is non-existant, maybe you'd like to make a translation for ADV - ACE Splint as well?
https://github.com/Pergor/ADV_Medical/blob/master/adv_aceSplint/stringtable.xml

**Comment by veteran29** [comment]
Sure thing! Will do soon.

**Comment by veteran29** [comment]
Unified whitespace by using https://github.com/bux/tabler for stringtable editing and added polish translation for Splint.

**Comment by Pergor** [comment]
Thank you very much! Translation is implemented and will be pushed with the next update!

**Pull request closed without merging**
