### PR TITLE
Add Chinese Translate

### PR DESCRIPTION
**Pull request by GodofMonkeys**
Add Chinese Translate.

### CODE REVIEW

**Comment by Pergor** [comment]
Will be implemented with next update, thank you for the translation!

**Comment by Pergor** [comment]
For the next update I have two new strings, would you mind translating them to Chinese as well, so I can include them directly?

''<Key ID="STR_ADV_ACECPR_AED_STATION_HINT_ON">
			<Original>You can use the Defibrillator during the next 12 seconds.</Original>
			<English>You can use the Defibrillator during the next 12 seconds.</English>
			<French>Tu peux utiliser le défibrillateur pendant les 12 prochaines secondes.</French>
			<German>Der Defibrillator kann in den nächsten 12 Sekunden eingesetzt werden.</German>
        </Key>
        <Key ID="STR_ADV_ACECPR_AED_STATION_HINT_OFF">
			<Original>Defibrillator deactivated.</Original>
			<English>Defibrillator deactivated.</English>
			<French>Défibrillateur désactivé.</French>
			<German>Defibrillator deaktiviert.</German>
        </Key>''

**Comment by GodofMonkeys** [comment]
@Pergor 
```
<Key ID="STR_ADV_ACECPR_AED_STATION_HINT_ON">
    <Original>You can use the Defibrillator during the next 12 seconds.</Original>
    <English>You can use the Defibrillator during the next 12 seconds.</English>
    <French>Tu peux utiliser le défibrillateur pendant les 12 prochaines secondes.</French>
    <German>Der Defibrillator kann in den nächsten 12 Sekunden eingesetzt werden.</German>
    <Chinese>你可以在12秒後再次使用除顫器。</Chinese>
    <Chinesesimp>你可以在12秒后再次使用除颤器。</Chinesesimp>
</Key>
<Key ID="STR_ADV_ACECPR_AED_STATION_HINT_OFF">
    <Original>Defibrillator deactivated.</Original>
    <English>Defibrillator deactivated.</English>
    <French>Défibrillateur désactivé.</French>
    <German>Defibrillator deaktiviert.</German>
    <Chinese>除顫器已停用。</Chinese>
    <Chinesesimp>除颤器已停用。</Chinesesimp>
</Key>
<Key ID="STR_ADV_ACECPR_SETTING_STATION">
    <Original>Stationary AED objects</Original>
    <English>Stationary AED objects</English>
    <French>Objets AED stationnaire</French>
    <German>Stationäre AED-Objekte</German>
    <Chinese>固定式AED物件</Chinese>
    <Chinesesimp>固定式AED物件</Chinesesimp>
</Key>
<Key ID="STR_ADV_ACECPR_SETTING_STATION_DESCRIPTION">
    <Original>Which objects can be used as a stationary AED (seperate by comma)?</Original>
    <English>Which objects can be used as a stationary AED (seperate by comma)?</English>
    <French>Quels objets peuvent être utilisés comme AED stationnaire (séparé par une virgule)?</French>
    <German>Welche Objekte können als stationärer AED eingesetzt werden (Aufzählung mit Komma)?</German>
    <Chinese>那些物件可以被當作是固定式AED(使用逗號做區隔)?</Chinese>
    <Chinesesimp>那些物件可以被当作是固定式AED(使用逗号做区隔)?</Chinesesimp>
</Key>
```

**Comment by GodofMonkeys** [comment]
I have a suggestion, can you extract the "Automated External Defibrillator" string as well ?
if you can there is the translate:

```
<Chinese>自動體外除顫器</Chinese>
<Chinesesimp>自动体外除颤器</Chinesesimp>
```

**Comment by Pergor** [comment]
Yeah, will do. Thank you very much!

**Comment by GodofMonkeys** [comment]
@Pergor Hi, I resolve conflict now, you can merge. ^^

I will push one more Pull request, let your item can add into ACE Medial box.

**Pull request closed without merging**
